env=qa
browser=chrome
headless=true
timeout.seconds=15
api.response.time.ms=10000
api.retry.count=3
api.retry.delay.ms=1500
retry.count=1
parallel.thread.count=4
cross.browser.browsers=chrome
default.email=qa.user123@mailinator.com
default.password=Engineer@09876
